project:
  type: website
  output-dir: docs

website:
  title: "Buylowsellsmart"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  python: "D:/PycharmProjects/finalProject/.venv/Scripts/python.exe"

