<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Buy Low / Sell High Strategy Optimization – Buylowsellsmart</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Buylowsellsmart</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#strategy-overview-design" id="toc-strategy-overview-design" class="nav-link active" data-scroll-target="#strategy-overview-design">Strategy Overview &amp; Design</a></li>
  <li><a href="#system-architecture-implementation" id="toc-system-architecture-implementation" class="nav-link" data-scroll-target="#system-architecture-implementation">System Architecture &amp; Implementation</a></li>
  <li><a href="#trading-logic-risk-management" id="toc-trading-logic-risk-management" class="nav-link" data-scroll-target="#trading-logic-risk-management">Trading Logic &amp; Risk Management</a></li>
  <li><a href="#parameter-optimization-system" id="toc-parameter-optimization-system" class="nav-link" data-scroll-target="#parameter-optimization-system">Parameter Optimization System</a>
  <ul class="collapse">
  <li><a href="#parameter-optimization-results" id="toc-parameter-optimization-results" class="nav-link" data-scroll-target="#parameter-optimization-results">Parameter Optimization Results</a></li>
  <li><a href="#trading-signal-examples" id="toc-trading-signal-examples" class="nav-link" data-scroll-target="#trading-signal-examples">Trading Signal Examples</a></li>
  <li><a href="#rsi-threshold-performance-comparison" id="toc-rsi-threshold-performance-comparison" class="nav-link" data-scroll-target="#rsi-threshold-performance-comparison">RSI Threshold Performance Comparison</a></li>
  </ul></li>
  <li><a href="#best-trade-case-analysis" id="toc-best-trade-case-analysis" class="nav-link" data-scroll-target="#best-trade-case-analysis">Best Trade Case Analysis</a></li>
  <li><a href="#performance-results-visualization" id="toc-performance-results-visualization" class="nav-link" data-scroll-target="#performance-results-visualization">Performance Results &amp; Visualization</a>
  <ul class="collapse">
  <li><a href="#detailed-trade-analysis" id="toc-detailed-trade-analysis" class="nav-link" data-scroll-target="#detailed-trade-analysis">Detailed Trade Analysis</a></li>
  <li><a href="#portfolio-performance-summary" id="toc-portfolio-performance-summary" class="nav-link" data-scroll-target="#portfolio-performance-summary">Portfolio Performance Summary</a></li>
  <li><a href="#strategy-visualization" id="toc-strategy-visualization" class="nav-link" data-scroll-target="#strategy-visualization">Strategy Visualization</a></li>
  </ul></li>
  <li><a href="#conclusions-future-work" id="toc-conclusions-future-work" class="nav-link" data-scroll-target="#conclusions-future-work">Conclusions &amp; Future Work</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Buy Low / Sell High Strategy Optimization</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sicong Chen123456789, Yuxin Wan </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="strategy-overview-design" class="level2">
<h2 class="anchored" data-anchor-id="strategy-overview-design">Strategy Overview &amp; Design</h2>
<ul>
<li><strong>Topic Chosen</strong>: Buy Low / Sell High Strategy with Robust Parameter Optimization</li>
<li><strong>Why This Strategy?</strong>
<ul>
<li>A proven strategy that combines multiple technical indicators for entry/exit signals</li>
<li>Balanced approach using both trend following and mean reversion principles</li>
<li>Comprehensive parameter optimization to enhance performance across market conditions</li>
</ul></li>
<li><strong>Goal</strong>: Optimize entry/exit signals &amp; risk management using advanced statistical techniques</li>
<li><strong>Domain Name</strong>: buylowsellsmart.com</li>
</ul>
<p><strong>Choice of Assets</strong>: - Highly liquid assets that respond well to technical analysis (e.g., AAPL) - Moderate to high volatility suitable for ATR-based risk management - Both trending and range-bound behavior for strategy testing - Multiple timeframes to validate strategy robustness</p>
<p><strong>Technical Features</strong>: - <strong>Moving Average Trend Confirmation</strong>: Using SMA 50/200 crossovers to establish trend direction - <strong>RSI (Relative Strength Index)</strong>: Identifying oversold/overbought conditions with adaptive thresholds - <strong>Bollinger Bands</strong>: Detecting price extremes and potential reversal zones - <strong>ATR-Based Risk Management</strong>: Dynamic stop-loss and take-profit levels based on current volatility - <strong>Detailed Trade Analysis</strong>: Metrics including win rate, profit factor, and consecutive wins/losses</p>
</section>
<section id="system-architecture-implementation" class="level2">
<h2 class="anchored" data-anchor-id="system-architecture-implementation">System Architecture &amp; Implementation</h2>
<p>The system follows a modular, component-based design with unified exception handling:</p>
<ul>
<li><strong>Data Acquisition</strong>: Fetching historical data with appropriate error handling</li>
<li><strong>Technical Analysis</strong>: Calculating various indicators using the TA library</li>
<li><strong>Signal Generation</strong>: Creating buy/sell signals based on optimized parameters</li>
<li><strong>Backtesting Engine</strong>: Simulating trades with precise execution logic</li>
<li><strong>Risk Management</strong>: Implementing dynamic stop-loss and take-profit mechanisms</li>
<li><strong>Performance Analysis</strong>: Detailed trade metrics and portfolio statistics</li>
<li><strong>Parameter Optimization</strong>: Grid search with comprehensive evaluation metrics</li>
<li><strong>Visualization System</strong>: Multi-layered charts for strategy assessment</li>
</ul>
<p>All components utilize a decorator-based exception handling system that ensures robust execution even when encountering unexpected data or market conditions.</p>
<p><strong>Data &amp; Tools</strong>: - Historical price data using Shinybroker API - Python with pandas, numpy, ta, matplotlib - Technical indicators: SMA, RSI, Bollinger Bands, ATR, MACD, OBV - Multi-panel charts for strategy assessment - Decorator-based unified error management</p>
</section>
<section id="trading-logic-risk-management" class="level2">
<h2 class="anchored" data-anchor-id="trading-logic-risk-management">Trading Logic &amp; Risk Management</h2>
<p><strong>Entry Conditions</strong>: - Trend confirmation (SMA50 &gt; SMA200) - Oversold condition (RSI &lt; optimized threshold, default 40) - Price at support (Close at/below lower Bollinger Band)</p>
<p><strong>Risk Parameters</strong>: - Stop-loss: ATR-multiplier (optimized, default 2.0) - Take-profit: ATR-multiplier (optimized, default 4.0) - Position sizing: Fixed percentage of portfolio (default 2%)</p>
<p><strong>Exit Signals</strong>: - Technical exit: RSI &gt; 70 (overbought) or Close &lt; SMA50 (trend reversal) - Risk management exit: Stop-loss or take-profit price levels reached</p>
<p><strong>Risk Management Approach</strong>: - Dynamic stop-loss based on ATR multiplier to adapt to market volatility - Dynamic take-profit targets proportional to risk taken - Trend reversal exit when price falls below SMA50 - Overbought exit when RSI exceeds 70 - Conservative 2% position sizing to limit exposure - Robust exception handling throughout the system</p>
</section>
<section id="parameter-optimization-system" class="level2">
<h2 class="anchored" data-anchor-id="parameter-optimization-system">Parameter Optimization System</h2>
<p><strong>Grid Search Implementation</strong>: - RSI thresholds: [30, 35, 40, 45] - ATR stop-loss multipliers: [1.5, 2.0, 2.5, 3.0] - ATR take-profit multipliers: [3.0, 4.0, 5.0]</p>
<p><strong>Performance Metrics</strong>: - Sharpe Ratio (primary optimization metric) - Win Rate - Maximum Drawdown - Annualized Return - Profit Factor (total wins / total losses)</p>
<p><strong>Optimization Process</strong>: - Minimum 5 trades required for parameter evaluation - Take-profit multiplier must exceed stop-loss multiplier - Parameter combinations evaluated primarily by Sharpe ratio - Detailed visualization of optimization results for decision making</p>
<section id="parameter-optimization-results" class="level3">
<h3 class="anchored" data-anchor-id="parameter-optimization-results">Parameter Optimization Results</h3>
<p>The table below summarizes the key results from our parameter optimization testing, highlighting how different parameter combinations affect performance metrics:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>RSI Threshold</th>
<th>ATR Stop</th>
<th>ATR Take</th>
<th>Total Trades</th>
<th>Win Rate</th>
<th>Total Return</th>
<th>Max Drawdown</th>
<th>Sharpe Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>30</td>
<td>1.5</td>
<td>3.0</td>
<td>3</td>
<td>33.33%</td>
<td>-0.13%</td>
<td>-0.14%</td>
<td>N/A</td>
</tr>
<tr class="even">
<td>35</td>
<td>1.5</td>
<td>3.0</td>
<td>6</td>
<td>50.00%</td>
<td>-0.13%</td>
<td>-0.15%</td>
<td>-0.83</td>
</tr>
<tr class="odd">
<td>35</td>
<td>2.0</td>
<td>4.0</td>
<td>6</td>
<td>50.00%</td>
<td>-0.13%</td>
<td>-0.15%</td>
<td>-0.83</td>
</tr>
<tr class="even">
<td>40</td>
<td>1.5</td>
<td>3.0</td>
<td>9</td>
<td>44.44%</td>
<td>-0.27%</td>
<td>-0.27%</td>
<td>-1.55</td>
</tr>
<tr class="odd">
<td>40</td>
<td>2.5</td>
<td>5.0</td>
<td>9</td>
<td>44.44%</td>
<td>-0.27%</td>
<td>-0.27%</td>
<td>-1.55</td>
</tr>
<tr class="even">
<td>45</td>
<td>2.0</td>
<td>4.0</td>
<td>9</td>
<td>44.44%</td>
<td>-0.27%</td>
<td>-0.27%</td>
<td>-1.55</td>
</tr>
</tbody>
</table>
<p><em>Best parameter combination: RSI=35, ATR Stop=1.5, ATR Take=3.0</em></p>
</section>
<section id="trading-signal-examples" class="level3">
<h3 class="anchored" data-anchor-id="trading-signal-examples">Trading Signal Examples</h3>
<p>Below is a sample of trading signals generated by our system for AAPL stock during the test period:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 29%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Date</th>
<th>Action</th>
<th>Price</th>
<th>Reason</th>
<th>Outcome</th>
<th>Profit/Loss</th>
<th>Return</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2025-04-03</td>
<td>BUY</td>
<td>203.19</td>
<td>RSI below threshold</td>
<td>Loss</td>
<td>-$145.80</td>
<td>-7.29%</td>
</tr>
<tr class="even">
<td>2025-04-04</td>
<td>SELL</td>
<td>188.38</td>
<td>Stop-loss triggered</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>2025-03-13</td>
<td>BUY</td>
<td>209.68</td>
<td>RSI below threshold</td>
<td>Win</td>
<td>+$36.33</td>
<td>+1.82%</td>
</tr>
<tr class="even">
<td>2025-03-14</td>
<td>SELL</td>
<td>213.49</td>
<td>Close below SMA50</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>2025-03-11</td>
<td>BUY</td>
<td>220.84</td>
<td>RSI below threshold</td>
<td>Loss</td>
<td>-$34.96</td>
<td>-1.75%</td>
</tr>
<tr class="even">
<td>2025-03-12</td>
<td>SELL</td>
<td>216.98</td>
<td>Close below SMA50</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>2025-01-21</td>
<td>BUY</td>
<td>222.64</td>
<td>RSI below threshold</td>
<td>Win</td>
<td>+$10.69</td>
<td>+0.53%</td>
</tr>
<tr class="even">
<td>2025-01-22</td>
<td>SELL</td>
<td>223.83</td>
<td>Close below SMA50</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>2025-01-16</td>
<td>BUY</td>
<td>228.26</td>
<td>RSI below threshold</td>
<td>Win</td>
<td>+$15.07</td>
<td>+0.75%</td>
</tr>
<tr class="even">
<td>2025-01-17</td>
<td>SELL</td>
<td>229.98</td>
<td>Close below SMA50</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>2025-01-13</td>
<td>BUY</td>
<td>234.40</td>
<td>RSI below threshold</td>
<td>Loss</td>
<td>-$9.56</td>
<td>-0.48%</td>
</tr>
<tr class="even">
<td>2025-01-14</td>
<td>SELL</td>
<td>233.28</td>
<td>Close below SMA50</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><em>Based on optimal parameters: RSI=35, ATR Stop=1.5, ATR Take=3.0</em></p>
</section>
<section id="rsi-threshold-performance-comparison" class="level3">
<h3 class="anchored" data-anchor-id="rsi-threshold-performance-comparison">RSI Threshold Performance Comparison</h3>
<p>This table compares the performance metrics across different RSI threshold values, holding other parameters constant (ATR Stop=2.0, ATR Take=4.0):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>RSI Threshold</th>
<th>Total Trades</th>
<th>Win Rate</th>
<th>Total Return</th>
<th>Ann. Return</th>
<th>Max Drawdown</th>
<th>Sharpe Ratio</th>
<th>Avg Trade Duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>30</td>
<td>3</td>
<td>33.33%</td>
<td>-0.13%</td>
<td>-0.13%</td>
<td>-0.14%</td>
<td>N/A</td>
<td>1.0 days</td>
</tr>
<tr class="even">
<td>35</td>
<td>6</td>
<td>50.00%</td>
<td>-0.13%</td>
<td>-0.13%</td>
<td>-0.15%</td>
<td>-0.83</td>
<td>1.0 days</td>
</tr>
<tr class="odd">
<td>40</td>
<td>9</td>
<td>44.44%</td>
<td>-0.27%</td>
<td>-0.27%</td>
<td>-0.27%</td>
<td>-1.55</td>
<td>1.0 days</td>
</tr>
<tr class="even">
<td>45</td>
<td>9</td>
<td>44.44%</td>
<td>-0.27%</td>
<td>-0.27%</td>
<td>-0.27%</td>
<td>-1.55</td>
<td>1.0 days</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="best-trade-case-analysis" class="level2">
<h2 class="anchored" data-anchor-id="best-trade-case-analysis">Best Trade Case Analysis</h2>
<p>Let’s analyze the most profitable trade from our backtest to understand the dynamics of a successful signal:</p>
<p><strong>AAPL Trade (March 13-14, 2025)</strong></p>
<p><em>Market Context:</em> - AAPL had been in a downtrend, dropping from $227.48 on March 10th to $209.68 on March 13th - RSI fell below our threshold, indicating oversold conditions - Price approached the lower Bollinger Band, suggesting potential support</p>
<p><em>Entry Details:</em> - Date: March 13, 2025 - Entry Price: $209.68 - RSI at Entry: 36.9 (below our threshold of 40) - Position Size: 2% of portfolio (approximately $2,000) - Stop Loss: Set at $205.18 (Entry - 1.5× ATR) - Take Profit: Set at $218.68 (Entry + 3.0× ATR)</p>
<p><em>Exit Details:</em> - Date: March 14, 2025 - Exit Price: $213.49 - Exit Reason: Close below SMA50 (trend reversal signal) - Holding Period: 1 day</p>
<p><em>Trade Outcome:</em> - Profit: +$36.33 - Return: +1.82% - Risk-Reward: Favorable, exited before reaching take-profit level but captured upside</p>
<p><em>Key Success Factors:</em> - Entry at relatively oversold levels - Quick price bounce from support level - Proper position sizing limiting exposure - Disciplined exit when trend signal reversed</p>
<p>This trade demonstrates that even in a challenging overall market environment, the strategy can identify short-term reversal opportunities. The short holding period is typical of the backtest results, where most positions were closed quickly due to SMA crossovers.</p>
</section>
<section id="performance-results-visualization" class="level2">
<h2 class="anchored" data-anchor-id="performance-results-visualization">Performance Results &amp; Visualization</h2>
<section id="detailed-trade-analysis" class="level3">
<h3 class="anchored" data-anchor-id="detailed-trade-analysis">Detailed Trade Analysis</h3>
<p>The table below presents the comprehensive analysis of all trades executed during our backtest period with the optimal parameters:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 32%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Trade Statistics</strong></td>
<td>Total Trades</td>
<td>6</td>
</tr>
<tr class="even">
<td></td>
<td>Win Rate</td>
<td>50.00% (3 wins, 3 losses)</td>
</tr>
<tr class="odd">
<td></td>
<td>Profit Factor</td>
<td>0.33</td>
</tr>
<tr class="even">
<td></td>
<td>Max Consecutive Wins</td>
<td>2</td>
</tr>
<tr class="odd">
<td></td>
<td>Max Consecutive Losses</td>
<td>1</td>
</tr>
<tr class="even">
<td><strong>Profitability</strong></td>
<td>Average Trade Profit</td>
<td>-$21.37</td>
</tr>
<tr class="odd">
<td></td>
<td>Average Win</td>
<td>+$20.70</td>
</tr>
<tr class="even">
<td></td>
<td>Average Loss</td>
<td>-$63.44</td>
</tr>
<tr class="odd">
<td><strong>Duration</strong></td>
<td>Average Holding Period</td>
<td>1.0 days</td>
</tr>
<tr class="even">
<td></td>
<td>Maximum Duration</td>
<td>1 day</td>
</tr>
<tr class="odd">
<td></td>
<td>Minimum Duration</td>
<td>1 day</td>
</tr>
<tr class="even">
<td><strong>Performance</strong></td>
<td>Total Return</td>
<td>-0.13%</td>
</tr>
<tr class="odd">
<td></td>
<td>Annualized Return</td>
<td>-0.13%</td>
</tr>
<tr class="even">
<td></td>
<td>Maximum Drawdown</td>
<td>-0.15%</td>
</tr>
</tbody>
</table>
<p><em>Note: Trade analysis based on optimal parameters (RSI=35, ATR Stop=1.5, ATR Take=3.0)</em></p>
</section>
<section id="portfolio-performance-summary" class="level3">
<h3 class="anchored" data-anchor-id="portfolio-performance-summary">Portfolio Performance Summary</h3>
<p>The summary below shows the actual portfolio performance metrics from our backtest period:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Testing Period</td>
<td>9 months (2024-2025)</td>
</tr>
<tr class="even">
<td>Initial Capital</td>
<td>$100,000</td>
</tr>
<tr class="odd">
<td>Final Portfolio Value</td>
<td>$99,870</td>
</tr>
<tr class="even">
<td>Total Return</td>
<td>-0.13%</td>
</tr>
<tr class="odd">
<td>Annualized Return</td>
<td>-0.13%</td>
</tr>
<tr class="even">
<td>Sharpe Ratio</td>
<td>-0.83</td>
</tr>
<tr class="odd">
<td>Max Drawdown</td>
<td>-0.15%</td>
</tr>
<tr class="even">
<td>Win/Loss Ratio</td>
<td>1.00 (even)</td>
</tr>
<tr class="odd">
<td>Average Daily Return</td>
<td>-0.001%</td>
</tr>
<tr class="even">
<td>Return Volatility</td>
<td>0.16%</td>
</tr>
<tr class="odd">
<td>Risk-Adjusted Return</td>
<td>Negative</td>
</tr>
</tbody>
</table>
<p><em>The backtest results reflect a challenging market period where most trades were closed due to trend reversals (price falling below SMA50). In practical implementations, additional filters would be applied to improve entry timing.</em></p>
</section>
<section id="strategy-visualization" class="level3">
<h3 class="anchored" data-anchor-id="strategy-visualization">Strategy Visualization</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="AAPL_trading_signals.png" class="img-fluid figure-img"></p>
<figcaption>Trading Strategy Visualization</figcaption>
</figure>
</div>
<p><em>Figure 1: Trading signals with price and RSI indicators</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="AAPL_portfolio_performance.png" class="img-fluid figure-img"></p>
<figcaption>Portfolio Performance</figcaption>
</figure>
</div>
<p><em>Figure 2: Portfolio value, drawdown analysis, and monthly returns heatmap</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="AAPL_trade_analysis.png" class="img-fluid figure-img"></p>
<figcaption>Trade Analysis</figcaption>
</figure>
</div>
<p><em>Figure 3: Trade distribution analysis showing profits, returns, and duration</em></p>
<p><strong>Advanced Metrics</strong>:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="advanced_metrics_analysis.png" class="img-fluid figure-img"></p>
<figcaption>Advanced Metrics Analysis</figcaption>
</figure>
</div>
<p><em>Figure 4: Advanced risk and return metrics analysis showing daily returns distribution, drawdown distribution, rolling returns and volatility, and rolling Sharpe ratio</em></p>
<p><strong>Parameter Optimization Results</strong>:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="parameter_optimization_results.png" class="img-fluid figure-img"></p>
<figcaption>Parameter Optimization Results</figcaption>
</figure>
</div>
<p><em>Figure 5: Analysis of parameter combinations showing Sharpe ratio, risk-return profile, and correlations</em></p>
</section>
</section>
<section id="conclusions-future-work" class="level2">
<h2 class="anchored" data-anchor-id="conclusions-future-work">Conclusions &amp; Future Work</h2>
<p><strong>Strategy Performance Assessment</strong>: - The strategy demonstrated consistent signal generation but showed negative returns (-0.13%) during the test period - Short holding periods (average 1 day) due to frequent trend reversals - Equal win/loss ratio (50%) but larger average losses compared to gains - Risk management worked effectively, limiting maximum drawdown to -0.15%</p>
<p><strong>Strategy Strengths</strong>: - Robust signal generation methodology - Effective risk management framework - Comprehensive analysis capabilities - Detailed visualization and analysis tools</p>
<p><strong>Future Enhancements</strong>: 1. Machine Learning Integration for parameter optimization 2. Multi-Asset Portfolio extension for diversification 3. Adaptive Parameters based on market regimes 4. Alternative Data incorporation (sentiment analysis, economic indicators) 5. Real-Time Implementation for live trading</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>